<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.InstallerManager provides APIs for installers to manage application restarts using Windows Restart Manager.</Description>
    <PackageTags>windows native restart-manager installer</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
</Project>
