<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.Shell32 provides logic of the Windows Shell32 API</Description>
    <PackageTags>windows native shell32</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Common\Dapplo.Windows.Common.csproj" />
  </ItemGroup>
</Project>
