<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.User32 provides logic of the Windows User32 API</Description>
    <PackageTags>windows native user32</PackageTags>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Common\Dapplo.Windows.Common.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Messages\Dapplo.Windows.Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="Dapplo.Log" Version="3.0.22" />
  </ItemGroup>
</Project>
