<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows has native code for accessing Windows, e.g getting the size/title/location of a window or monitoring the title changes of windows.</Description>
    <PackageTags>windows native desktop</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Common\Dapplo.Windows.Common.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Com\Dapplo.Windows.Com.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.DesktopWindowsManager\Dapplo.Windows.DesktopWindowsManager.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Gdi32\Dapplo.Windows.Gdi32.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Icons\Dapplo.Windows.Icons.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Input\Dapplo.Windows.Input.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Kernel32\Dapplo.Windows.Kernel32.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Messages\Dapplo.Windows.Messages.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.User32\Dapplo.Windows.User32.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapplo.Log" Version="3.0.22" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
  </ItemGroup>
</Project>
