<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.Gdi32 bringt Gdi32 and GdiPlus functionality.</Description>
    <PackageTags>windows native gdi</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Common\Dapplo.Windows.Common.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.User32\Dapplo.Windows.User32.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapplo.Log" Version="3.0.22" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>
</Project>
