<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.Advapi32 is a library for accessing the Advanced Windows 32 Base API</Description>
    <PackageTags>windows native Advapi32</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>
</Project>
