<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.Input provides code to generate and get input from keyboard and mouse</Description>
    <PackageTags>windows native input</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Common\Dapplo.Windows.Common.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Messages\Dapplo.Windows.Messages.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.User32\Dapplo.Windows.User32.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
</Project>
