<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapplo.Windows.EmbeddedBrowser is a small library which helps to embed the Internet Explorer in the most recent version.</Description>
    <PackageTags>windows native browser embedded ie</PackageTags>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Com\Dapplo.Windows.Com.csproj" />
  </ItemGroup>
</Project>
