// Copyright (c) Dapplo and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace Dapplo.Windows.Input.Structs;

/// <summary>
/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// See <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/ms646269.aspx">HARDWAREINPUT structure</a>
/// </summary>
[StructLayout(LayoutKind.Sequential)]
[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
[SuppressMessage("ReSharper", "ArrangeAccessorOwnerBody")]
public struct HardwareInput
{
	private uint _uMsg;
	private ushort _wParamL;
	private ushort _wParamH;

	/// <summary>
	/// The message generated by the input hardware (uMsg).
	/// </summary>
	public uint Message
	{
		get { return _uMsg; }
		set { _uMsg = value; }
	}

	/// <summary>
	/// The low-order word of the lParam parameter for uMsg (wParamL).
	/// </summary>
	public ushort ParamL
	{
		get { return _wParamL; }
		set { _wParamL = value; }
	}

	/// <summary>
	/// The high-order word of the lParam parameter for uMsg (wParamH).
	/// </summary>
	public ushort ParamH
	{
		get { return _wParamH; }
		set { _wParamH = value; }
	}
}