<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net480;net10.0-windows</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dapplo.Windows.Clipboard\Dapplo.Windows.Clipboard.csproj" />
    <ProjectReference Include="..\Dapplo.Windows.Messages\Dapplo.Windows.Messages.csproj" />
    <ProjectReference Include="..\Dapplo.Windows\Dapplo.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
</Project>
